### ISSUE TITLE
Write-up vulnerabilities

### ISSUE THREAD

**Issue by dugdug36** [sysdiglabs/dummy-vuln-app#4]
Hello, 

Thanks for you app, do you have write-up solution of vulnerabilities ?. 
@leodido @airadier @nestorsalceda @tembleking @fntlnz

**Comment by airadier** [comment]
Hi @dugdug36, this is just an example container image containing vulnerabilities for image scanning demo purposes. It started with some vulnerabilities found in the python numpy package, but as it is using an old Debian version it contains hundreds of known vulnerabilities in old packages. You can see details for each vulnerability by following the vulnerability description URL, from the list of vulnerabilities in one the image scan executions:

https://github.com/sysdiglabs/dummy-vuln-app/runs/1602779356?check_suite_focus=true
